### ISSUE TITLE
Script for testing trained model on own sample recording

### ISSUE THREAD

**Issue by akshayaCap** [yongxuUSTC/sednn#16]
Hi Yong Xu,
I have finished training model. I am stuck on testing the output of trained model on new recording. Is there a script for this? Or if someone could point out the changes in prepare_data.py and main_dnn.py for this.
The issue is I have a recording with noise so cannot define signal to noise ratio.

Thank you
Akshaya

**Comment by qiuqiangkong** [comment]
Hi Akshaya,


    For testing the new audio, you may extract the features first, then apply the model on the feature. Please see the code here for inference https://github.com/yongxuUSTC/sednn/blob/master/mixture2clean_dnn/main_dnn.py#L172



Best wishes,


Qiuqiang

________________________________
