### ISSUE TITLE
About global variance

### ISSUE THREAD

**Issue by jeongHwarr** [yongxuUSTC/sednn#19]
Hi Yong Xu,

I'm really appreciate for your project. I have some questions. 
First, does this project include global variance equalization? If so, which part?

and I'm trained this model with my data. (I think about 20 hours data for train) However, PESQ results with enhancemented data were worse than comparing noisy and clean. 

I founded that enhancemented waves are strange..

This is mixed audio below.
![image](https://user-images.githubusercontent.com/16534413/45803808-7920c400-bcf5-11e8-82bd-91e47968649c.png)

and this is enhancemented audio below.
![image](https://user-images.githubusercontent.com/16534413/45803780-61494000-bcf5-11e8-9571-5a8cad148340.png)

Why did this result come out?

Thank you!

**Comment by yongxuUSTC** [comment]
Hi,

Global variance equalization is not included in this sednn project.
Your result is magnitude clipping.

You should do some normalization, and also control the magnitude of speech when stored into a 16bit wav

Best regards,
yong



----------------------------------------------------------
Yong XU
 
From: jeonghwaYoo
Date: 2018-09-20 00:53
To: yongxuUSTC/sednn
CC: Subscribed
Subject: [yongxuUSTC/sednn] About global variance (#19)
Hi Yong Xu,
I'm really appreciate for your project. I have some questions.
First, does this project include global variance equalization? If so, which part?
and I'm trained this model with my data. (I think about 20 hours data for train) However, PESQ results with enhancemented data were worse than comparing noisy and clean.
I founded that enhancemented waves are strange..
This is mixed audio below.
and this is enhancemented audio below.
Why did this result come out?
Thank you!

**Comment by maogewudi007** [comment]
> Hi Yong Xu,
> 
> I'm really appreciate for your project. I have some questions.
> First, does this project include global variance equalization? If so, which part?
> 
> and I'm trained this model with my data. (I think about 20 hours data for train) However, PESQ results with enhancemented data were worse than comparing noisy and clean.
> 
> I founded that enhancemented waves are strange..
> 
> This is mixed audio below.
> ![image](https://user-images.githubusercontent.com/16534413/45803808-7920c400-bcf5-11e8-82bd-91e47968649c.png)
> 
> and this is enhancemented audio below.
> ![image](https://user-images.githubusercontent.com/16534413/45803780-61494000-bcf5-11e8-9571-5a8cad148340.png)
> 
> Why did this result come out?
> 
> Thank you!

I meet the same problem...Do you solve it? 
Thank you!!!

**Comment by qiuqiangkong** [comment]
Hi,


    For the clip phenomenon, please check if you applied the normalization (subtract mean and divide the standard value) in both the training and testing dataset correctly.


Best wishes,


Qiuqiang

________________________________

**Comment by maogewudi007** [comment]
@qiuqiangkong 
 I met the plobblem in test dataset. I make the test dataset according to the code. I notice in the preprocessing, you use the normalization. But in the "recover wav" preprocessing, there is no code about normalization. Maybe the reason is that. I will thankful if you fix it! At the mean time, I notice the code don't have inference part.(I write the part, but the experiment result still has clip phenomenon.)

**Comment by jeonghwaYoo** [comment]
I solved this problem. I modified the inference part in main_dnn.py. In Recover enhanced wav part, there is some part to compensate the amplitude.  I commented out 's *= np.sqrt((np.hamming(n_window)**2).sum())'. As a result, I able to extract the resulting file without the clip. But I think that normalization seems to be a fundamental solution. In my case, the amplitude of each audio was too different. So it seems that the clip phenomenon occurred in audio.

**Comment by qiuqiangkong** [comment]
Glad to hear that. By the way pay attention in the testing stage the system should use the normalization scalar calculated from the training stage.


Best wishes,


Qiuqiang

________________________________

**Comment by yongxuUSTC** [comment]
Hi,

If you test the real-world noisy speech, please use my another code:
https://github.com/yongxuUSTC/DNN-Speech-enhancement-demo-tool
It has already considered the magnitude difference and better normalization
strategy.

If you really want to use the python code, i suggest you can subtract the
utterance mean first, then global mean-var norm. During the reconstruction
stage, you can pred*STD+Global_Mean + utterance mean.

Best regards,
yong

**Comment by jeonghwaYoo** [comment]
Thank you! However, I have some more questions. 
In the function named inference in main_dnn.py, you have not used the alpha value you used to normalize. Is it okay if this is not used? And I want to know the exact meaning of the scaler value. 
What method is used to scale?

**Comment by qiuqiangkong** [comment]
Hi, we subtract the mean and divide the standard value of the input, for both training and inference. I think the alpha you mentioned is just a mixing coefficient in the mixing procedure.


Best wishes,


Qiuqiang

________________________________

**Comment by zyy341** [comment]
Hi，I want to know the meaning of utterance mean. In my view，utterance mean is the mean of each T-F bin of clean speech. Could you be so kind as to provide me with some help on the above-mentioned problem? Thank you for your kindness.@yongxuUSTC 

> Hi, If you test the real-world noisy speech, please use my another code: https://github.com/yongxuUSTC/DNN-Speech-enhancement-demo-tool It has already considered the magnitude difference and better normalization strategy. If you really want to use the python code, i suggest you can subtract the utterance mean first, then global mean-var norm. During the reconstruction stage, you can pred*STD+Global_Mean + utterance mean. Best regards, yong

**Comment by yongxuUSTC** [comment]
Hi,

Utterance mean is the average of each frames. Its dimension is (257,1)   ,
257 is the dimension for difference frequency bin.

yong
