### ISSUE TITLE
Problem with "magnitude" mode

### ISSUE THREAD

**Issue by hangtingchen** [yongxuUSTC/sednn#21]
Hi Yong Xu,
I have read your code and meet some problem of the "magnitude" mode in func calc_sp 

https://github.com/yongxuUSTC/sednn/blob/c7efa60200f53f7b6653abb7051f6b39cbbc413b/mixture2clean_dnn/prepare_data.py#L261

The operation "astype" just throws away the imag part of a complex, which i have tested under numpy 1.13.3. Use np.abs to take magnitude. Is this a bug or something else ?

**Comment by qiuqiangkong** [comment]
Hi,


    if the mode is set as 'magnitude', then the x obtained from [f, t, x] = signal.spectral.spectrogram is np.float64, not complex type. Then the x = x.astype(np.float32) is only used to reduce the disk usage to save the features.


Best wishes,


Qiuqiang

________________________________

**Comment by hangtingchen** [comment]
got it, thanks a lot
