### ISSUE TITLE
Wrong noise trunication?

### ISSUE THREAD

**Issue by DinoTheDinosaur** [yongxuUSTC/sednn#23]
In _prepare_data.py_ in _calculate_mixture_features_
```
# Truncate noise to the same length as speech. 
else:
    noise_audio = noise_audio[noise_onset : noise_offset]
```
Shouldn't the range here be `noise_audio[:len(speech_audio)]` for instance? Otherwise it results in shapes mismatch later in the code.

**Comment by qiuqiangkong** [comment]
Hi, could you point out which line is the code? Many thanks!


Best wishes,


Qiuqiang

________________________________

**Comment by DinoTheDinosaur** [comment]
[https://github.com/yongxuUSTC/sednn/blob/c7efa60200f53f7b6653abb7051f6b39cbbc413b/mixture2clean_dnn/prepare_data.py#L158](Here)

**Comment by DinoTheDinosaur** [comment]
Yes, you're right, I see it in the code now.

Strangely, this part threw an error before the adjustments... Maybe there are some environment issues (I work in python 3). I guess I will look into the problem in detail some other time, closing the issue for now
