### ISSUE TITLE
about stoi

### ISSUE THREAD

**Issue by only-yipie** [yongxuUSTC/sednn#44]
您好，麻烦再请教一个问题，我发现经过Dnn增强过的语音客观可懂度stoi值反倒下降了，然后我将网络换成rnn，也遇到了这个问题。请问您遇到过这个问题么？可能的原因是什么呢？
期待您的回复，祝您生活愉快！
@qiuqiangkong

**Comment by qiuqiangkong** [comment]
您好，我当时主要观察了PESQ值，如果STOI值反而下降了，说明有些信息在增强的时候丢失了。


Best wishes,


Qiuqiang

________________________________

**Comment by only-yipie** [comment]
您好，那这个信息丢失，您觉得更可能是在哪个过程呢？是网络设计的问题呢？还是说数据预处理或者语音信号恢复的过程中？

**Comment by yongxuUSTC** [comment]
请问你有没有观测PESQ，PESQ是否升高了吗？如果PESQ都没有变好，或者提升很小，在STOI上就很难体现出来，因为STOI的范围更小，在0-1之间

**Comment by only-yipie** [comment]
@yongxuUSTC pesq有提升，平均下来大概是0.2-0.3这样子
